Fix for PHP8; no count() on stdClass
PoetOS/moodle-mod_questionnaire pull request #395
Opened 2022-04-08 03:44 UTC by nwp90

PHP8 does not allow count() on stdClass, so initialise haschildren to null, check for that and use a more complicated test for emptiness on haschildren.

2022-10-05 05:46 UTC, mwehr commented
Voting for integration

2022-10-21 15:28 UTC, mchurchward commented on questions.php
> +            if ($haschildren !== null and (count($haschildren->directs) + count($haschildren->indirects)) > 0) {
The term "and" should be replaced by "&&".

2022-10-21 15:48 UTC, mchurchward requested changes
Can you apply the code changes I have highlighted?
I would recommend creating a new branch from MOODLE_311_STABLE and resubmitting a new PR in order to get a clean set of commits.

2022-10-21 15:48 UTC, mchurchward commented on questions.php
> +$haschildren = null;
This line can be deleted completely, in combination with the suggestions below.

2022-10-21 15:48 UTC, mchurchward commented on questions.php
> +            if ($haschildren !== null and (count($haschildren->directs) + count($haschildren->indirects)) > 0) {
The block starting at "if ($questionnairehasdependencies) {" can be simplified down to:

```
            $action = "confirmdelquestion";
            if ($questionnairehasdependencies) {
                // Important: due to possibly multiple parents per question
                // just remove the dependency and inform the user about it.
                $haschildren = $questionnaire->get_all_dependants($qid);
                if (count($haschildren->directs) + count($haschildren->indirects) > 0) {
                    $action = "confirmdelquestionparent";
                }
            }

```
The $haschildren will always be a stdClass with "directs" and "indirects" properties, so we can just check the "questionnairehasdependencies" boolean to determine the rest.

2022-12-20 18:52 UTC, mchurchward commented on questions.php
> +            if ($haschildren !== null and (count($haschildren->directs) + count($haschildren->indirects)) > 0) {
This was already implemented in MOODLE_400_STABLE as part of https://github.com/PoetOS/moodle-mod_questionnaire/pull/442. I will backport it.

2022-12-20 18:52 UTC, closed without merging